meta:
  whatsapp:
    base-url: https://graph.facebook.com/v18.0
    phone-number-id: 1069373972919955
    token: EAALbVfhjYpABQZBOLKSDchgG54ZCYwX7DPQmZAZCViLzVTGjMBAWYDh3ABLc7yDJyoH5h8LQjY1INVKKDdHmonR55RNZAqk3I7F1liqEiNPY7GnEr7HAKYxyHmMUwCUaphfarmcghFQAZA7irUT5IRbY4V5qmZCTLwHuvxpzuciKJwUWs34AQWp9hykOpNkS41GqDWtwUfUvbkjpzJ3MO1wjcV8EuIsUpClGZCqQn689WzfTzGCu46oXYWwT6Aal6SVij4WqxrWw6CE8mSDmOclk4gZDZD