meta:
  whatsapp:
    base-url: https://graph.facebook.com/v18.0
    phone-number-id: 1069373972919955
    token: EAALbVfhjYpABQ7s5WMAoMwZAvB7t3alBmDvMRPTidPZCzlz1Ln1BVu5jwfqCR0jqYDqBJNVYCfx4zSB9srQf31BBJrkOxBAZCIIQqXzrRAzr6XfjPmDfw1ZCLv1LGoVDNnQEZBfr8PwJuUtBNCOXe0HiNAPZA7tR9Xmp8TnpQkV8knLaGc8MhdKx5H5ZAcAxNsc4cjbVtZA68RNIC5OdIdIrc4tvIhrAMXSbGLNxSPlmWT6BLcwX00ZBwb39nNZCwGyZC0rHilZBBZC6qKE1FSqzp6BJly2wUxs4WOLZCwfmPaDgZDZD