meta:
  whatsapp:
    base-url: https://graph.facebook.com/v18.0
    phone-number-id: 1069373972919955
    token: EAALbVfhjYpABQZCNdPv0qrfqaIOed9S5OHUPZAyjEc1cDfnXK7pLW4xQgHUYvUAWYyDhREPieMR6PyRaaNOmQHTfhf7Gg5gBHXHxnXZAQ1opztmyF9VZBQmu8bltr9ysSiDoXZAOtWhFmxlTeAZBXSZC8lvdCbepdEduBVgZAZCc38MmT0sD7dLFuhDB385ZAnjjhKhB3kJZBnnpdEjRt6TZADdI89BlGz2l0CdIOgYGZBsz7oZCH2pmzN5JGnmtZBW405TL5zE0kPHOuAZAQR1ZCJAos8ZBwUpgZDZD